#!/usr/bin/env node
// Refreshes generated rule snapshots in shared/rules from their public sources.
// Run before each release: `node scripts/gen-rules.mjs`
//   - ČNB bank codes (kody_bank_CR.csv) → shared/rules/bank-codes-cz.json
// The CERT.PL warning list snapshot is added in M2, when the engine starts using it.

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CNB_URL = 'https://www.cnb.cz/cs/platebni-styk/.galleries/ucty_kody_bank/download/kody_bank_CR.csv';

async function bankCodes() {
  const res = await fetch(CNB_URL);
  if (!res.ok) throw new Error(`ČNB CSV: HTTP ${res.status}`);
  const text = (await res.text()).replace(/^﻿/, '');
  const [header, ...lines] = text.split(/\r?\n/).filter(Boolean);
  if (!header.startsWith('Kód platebního styku;')) throw new Error(`Unexpected ČNB header: ${header}`);
  const banks = {};
  for (const line of lines) {
    const [code, name, bic, certis] = line.split(';').map((s) => s.trim());
    if (!/^\d{4}$/.test(code)) continue;
    banks[code] = { name, bic: bic || null, certis: certis || null };
  }
  const out = {
    schemaVersion: 1,
    source: CNB_URL,
    retrieved: new Date().toISOString().slice(0, 10),
    note: 'Generated by scripts/gen-rules.mjs — do not edit by hand.',
    banks,
  };
  await writeFile(path.join(root, 'shared/rules/bank-codes-cz.json'), JSON.stringify(out, null, 2) + '\n');
  console.log(`bank-codes-cz.json: ${Object.keys(banks).length} banks`);
}

await bankCodes();
