// swift-tools-version: 6.0
// BQUI: the result sheet of Bezpečné QR — verdict, risk meter, type cards, reasons and actions.
// Extension-safe (also runs inside the share extension): no UIApplication, no openURL; every side
// effect goes through `ResultActionHandler`. Strings come from prototype/js/i18n.js via
// scripts/gen-ui-strings.mjs.
import PackageDescription

let package = Package(
    name: "BQUI",
    defaultLocalization: "cs",
    platforms: [.iOS(.v18)],
    products: [
        .library(name: "BQUI", targets: ["BQUI"]),
    ],
    dependencies: [
        .package(path: "../BQCore"),
    ],
    targets: [
        .target(
            name: "BQUI",
            dependencies: [.product(name: "BQCore", package: "BQCore")],
            exclude: [
                // Input of scripts/gen-ui-strings.mjs, merged into ui-strings.json.
                "Resources/ios-strings.overlay.json",
            ],
            resources: [
                // Generated by scripts/gen-ui-strings.mjs — do not edit by hand.
                .copy("Resources/ui-strings.json"),
            ]
        ),
        .testTarget(
            name: "BQUITests",
            dependencies: ["BQUI", .product(name: "BQCore", package: "BQCore")]
        ),
    ]
)
